### ISSUE TITLE
I broke the board

### ISSUE THREAD

**Issue by Super-toad65** [ABXD-4-0/ABXD-4.0#4]
Ugh. i dunno what. i'm fixing karma stuff and then the software gets crazy.

Apparently, the karma recalculation function messes up stuff and ugh -.- 

i thought this snippet was enough for fixing that... -.-

also, it's still possible to post, it just shows a blank page 

`//NSMBHD-styled karma
function recalculateKarma($uid)
{
    $karma = 0;
	$karmaWeights = array(5, 10, 10, 15, 15);
	$rKarma = Query("select powerlevel, up from {uservotes} left join {users} on id=voter where uid={0} and powerlevel > -1", $uid);
	while($k = Fetch($rKarma))
	{
		if($k['up'])
			$karma += $karmaWeights[$k['powerlevel']];
		else
			$karma -= $karmaWeights[$k['powerlevel']];
	}
	
	$karma += 10*fetchResult("
					select count(*) 
					from {postplusones} l
					left join {posts} p on l.post=p.id
					where p.user={0}", $uid);
	
	$karma -= 15*fetchResult("
					select count(*) 
					from {posts}
					where user={0} and deleted=1", $uid);
	$karma -= 20*fetchResult("
					select count(*) 
					from {threads}
					where user={0} and forum={1}", $uid, Settings::get("trashForum"));
	$karma -= 30*fetchResult("
					select count(*) 
					from {threads}
					where user={0} and forum={1}", $uid, Settings::get("hiddenTrashForum"));
	$karma += 1*fetchResult("
					select count(*) 
					from {threads}
					where user={0}", $uid);
	$karma += fetchResult("
					select count(*) 
					from {posts}
					where user={0}", $uid)/2;
	
	Query("update {users} set karma={0} where id={1}", $karma, $uid);
	return $karma;
}`

**Comment by StapleButter** [comment]
just admit you can't code for shit

**Comment by phase** [comment]
Wrap the code in three backticks instead of one.

@StapleButter He's trying his hardest. I get ThenTheSoftwareGetsCrazyExceptions all the time.

**Comment by Super-toad65** [comment]
derp.

I preferred remove it anyways, morons just abuse it -.-
